# Generated by Django 3.0.8 on 2020-07-30 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tasker_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=150)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.TaskSeeker')),
            ],
        ),
    ]
