# Generated by Django 3.0.8 on 2020-08-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasker',
            name='completed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
