# Generated by Django 3.0.8 on 2020-08-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_tasker_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('JP', 'Japanese'), ('EN', 'English'), ('JE', 'English / Japanese')], default='EN', max_length=2),
        ),
    ]
