# Generated by Django 3.0.8 on 2020-08-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200802_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasker',
            name='completed',
            field=models.IntegerField(default=0),
        ),
    ]
