# Generated by Django 3.0.8 on 2020-09-06 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0005_auto_20200803_0309'),
        ('chat', '0002_auto_20200906_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_created', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(max_length=200)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.ScheduleBooking')),
                ('user_received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('user_sent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
