# Generated by Django 3.0.8 on 2020-07-29 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulebooking',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.TaskSeeker'),
        ),
        migrations.AddField(
            model_name='schedulebooking',
            name='tasker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tasker'),
        ),
    ]
