# Generated by Django 3.0.8 on 2020-07-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200729_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulebooking',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
